### ISSUE TITLE
Default colour not working

### ISSUE THREAD

**Issue by darylknight** [riasvdv/craft-colour-swatches#13]
If you create a colour swatched field and select one of the colours to be "Default", it doesn't actually get selected as the default colour. It appears to in the CMS, but the front end outputs nothing.

**Comment by Rias500** [comment]
Fixed in 1.1.4, thanks for reporting!

**Comment by kevinmu17** [comment]
This issue is back in 1.2.2, I have a colour-swatches.php config with a default: true on a color, it's shows in Craft cms that it is selected, but when saving it is empty and not showing front end. The user needs to switch back and forth to make it work.

**Comment by craftedsystems** [comment]
Same here. Default color results in an empty string. Switching back and forth required to get a valid value.
Pease reopen issue. Thx

**Comment by JayBox325** [comment]
Same for me, too. Looking forward to an update. Thanks for working on it @riasvdv 👍🏻

**Comment by JayBox325** [comment]
@riasvdv, I'm still having this issue and it's something my client is getting frustrated with. Do you have an update/potential time frame for me to pass onto them to put their minds at ease that this is being looked into?

Thanks.

**Comment by riasvdv** [comment]
Should be fixed in 1.2.5

**Comment by paulgoodfield** [comment]
Am also having this issue:

Craft Version: 3.3.19
Plugin Version: 1.2.7

Here is my `colour-swatches.php` config file:

```php
<?php
return [
	'colours' => [
		[
			'label'   => 'Coal Dark',
			'color'   => '#141A1E',
			'default' => true
		],
		[
			'label'   => 'Coal Light',
			'color'   => '#1D252D',
			'default' => false
		],
		[
			'label'   => 'Coal Grey',
			'color'   => '#5A5E61',
			'default' => false
		],
		[
			'label'   => 'Plum',
			'color'   => '#5A2D58',
			'default' => false
		],
		[
			'label'   => 'Wine',
			'color'   => '#A12242',
			'default' => false
		]
	]
];
```

First colour in config file is defined with `'default' => true`. Have created a Colour Swatches field in CMS and defined it as **required** in a section. When I create a new entry in that section, the default colour in the field is displaying as selected (i.e. has an orange ring around it), and I can save the entry without selecting any of the colours.

On the front-end, when I do `{{ dump(entry.fieldHandle.color) }}` it just outputs an empty string.

Worth noting that I'm using the field inside a matrix block. Not sure if that has any bearing on the issue.
